spring:
  datasource: #数据库的配置
    username: root #数据库的账号
    password: Beijing.20011025 #数据库的密码
    url: jdbc:mysql://localhost:3306/mallcore?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=America/New_York
mybatis-plus: #操作数据库的ORM框架 mybatis
  mapper-locations: mapper/*.xml #配置对于的mapper文件位置
  global-config:  #mybatis的全局配置
    db-config:    #数据库的配置
      table-prefix:   #表前面是否加前缀  如果不配置为空 会导致查询的sql表前面带有特定 前缀
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false         #是否转换成大小写
  type-aliases-package: com.example.web.entity  #实体存储的包位置
